# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bf4573d9beed115f6d9abad4531e6efb30078f0da6a427da093e8792476078251294a5c4b9352a3866b0ac71c5fb584b52c1cf1942958be63523baf943ffa03

test:
  secret_key_base: cce86b4a3fdda34cd44e1bc7b5ef0f1c0063a448f95bf953a3dba347d4c8c05019507abcc8d4525e2df9ac4e077034ad6d0bc59647f40370f8a37cfbaa71c55b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
